title: Create a link to another webpage
hero_image: images/banner.png
description: Create a link to another webpage.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Create a link to another webpage
