title: Maak een link naar een andere webpagina
hero_image: images/banner.png
description: Maak een link naar een andere webpagina.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Maak een link naar een andere webpagina
