title: Créer un lien vers une autre page web
hero_image: images/banner.png
description: Crée un lien vers une autre page web.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Créer un lien vers une autre page web
